src/Customer/Entities/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCCustomer.Entities
{
    public class Customer
    {
        public int Id { get; set; }

        [Required, MaxLength(80)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required, MaxLength(80)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [EmailValidation]
        public string Email { get; set; }

        public string FavoriteColor { get; set; }
    }
}

src/Customer/Entities/CustomerDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace MVCCustomer.Entities
{
    public class CustomerDbContext : DbContext
    {
        public CustomerDbContext(DbContextOptions<CustomerDbContext> options)
            : base(options)
        {
        }

        public DbSet<Customer> Customers { get; set; }

        protected override void OnModelCreating (ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customer>()
                .HasAlternateKey(x => x.Email)
                .HasName("AlternateKey_Email");
        }
    }
}

src/Customer/Entities/EmailValidation.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using MVCCustomer.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCCustomer.Entities
{
    public class EmailValidation : ValidationAttribute//, IClientModelValidator
    {
        private string _email;
        private ICustomerData _customerData;

        public EmailValidation()
        {
        }

        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var customer = (Customer)value;

            if (_customerData.GetAll().Any(x => x.Email == customer.Email))
            {
                return new ValidationResult("Email address not unique. Please try again with a different email.");
            }

            return ValidationResult.Success;
        }
    }
}

src/Customer/ViewModels/CustomerEditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MVCCustomer.ViewModels
{
    public class CustomerEditViewModel
    {
        [Required, MaxLength(80)]
        public string FirstName { get; set; }

        [Required, MaxLength(80)]
        public string LastName { get; set; }

        [Required]
        public string Email { get; set; }

        public string FavoriteColor { get; set; }
    }
}

src/Customer/ViewModels/CustomerViewModel.cs
using MVCCustomer.Entities;
using System.Collections.Generic;

namespace MVCCustomer.ViewModels
{
    public class CustomerViewModel
    {
        public IEnumerable<Customer> Customers { get; set; }
    }
}

src/Customer/Controllers/CustomerController.cs
using MVCCustomer.Entities;
using MVCCustomer.Services;

using Microsoft.AspNetCore.Mvc;
using MVCCustomer.ViewModels;
using System.Linq;
using System;

namespace MVCCustomer.Controllers
{
    public class CustomerController : Controller
    {
        public ICustomerData _customerData;

        public CustomerController(ICustomerData customerData)
        {
            _customerData = customerData;
        }

        public ViewResult Index()
        {
            var model = new CustomerViewModel();
            model.Customers = _customerData.GetAll();

            return View(model);
        }

        //public ViewResult Index(string errorMessage)
        //{
        //    var model = new CustomerViewModel();
        //    model.Customers = _customerData.GetAll();

        //    return View(model);
        //}

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _customerData.Get(id);

            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        } 

        [HttpPost]
        public IActionResult Edit(int id, CustomerEditViewModel input)
        {
            var customer = _customerData.Get(id);

            if (customer != null && ModelState.IsValid)
            {
                customer.FirstName = input.FirstName;
                customer.LastName = input.LastName;
                customer.Email = input.Email;
                customer.FavoriteColor = input.FavoriteColor;

                _customerData.Commit();

                return RedirectToAction("Details", new { id = customer.Id });
            }

            return View(customer);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CustomerEditViewModel model)
        {
            var result = TryValidateModel(model);

            if (ModelState.IsValid)
            {
                var customer = new Customer();
                customer.FirstName = model.FirstName;
                customer.LastName = model.LastName;
                customer.Email = model.Email;
                customer.FavoriteColor = model.FavoriteColor;
                
                if (_customerData.Add(customer) == false)
                {

                    return View("ErrorEmail", customer);
                }

                _customerData.Commit();

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Details(int id)
        {
            var model = _customerData.Get(id);

            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

src/Customer/Views/Customer/Create.cshtml
@model  Customer
@{
    ViewBag.Title = "Create a customer";
}

<h1>Create a customer</h1>

@using (Html.BeginForm())
{
    <div>
        First Name: @Html.EditorFor(m => m.FirstName)
        @Html.ValidationMessageFor(m => m.FirstName)
        <br />
        Last Name: @Html.EditorFor(m => m.LastName)
        @Html.ValidationMessageFor(m => m.LastName)
        <br />
        Email Address: @Html.EditorFor(m => m.Email)
        @Html.ValidationMessageFor(m => m.Email)
        <br />
        Favorite Color: @Html.EditorFor(m => m.FavoriteColor)
    </div>
    <div>
        <input type="submit" value="Save" />
    </div>
}

src/Customer/Views/Customer/ErrorEmail.cshtml
@{
    ViewBag.Title = "Home";
}

<h1><font color="red">Duplicate email address found. Please use a different email.</font></h1>

@Html.Partial("Create")

src/Customer/Views/Customer/Index.cshtml
@model MVCCustomer.ViewModels.CustomerViewModel

@{
    ViewBag.Title = "Home";
}

<h1>Welcome!</h1>

@if (Model.Customers.Any() == false)
{
    <h2>No Customers yet. Try adding a customer!</h2>
}
else {
    <h2>Current customers</h2>
}

@foreach (var customer in Model.Customers)
{
    @Html.Partial("_Summary", customer)
}

<div>
    <a asp-action="Create">Create a customer</a>
</div>

src/Customer/Views/Customer/_Summary.cshtml
@model Customer

<section class="panel panel-default">
    <div class="panel-body">
        First Name: @Model.FirstName <br />
        Last Name: @Model.LastName <br />
        Email: @Model.Email <br />
        Favorite Color: @Model.FavoriteColor
    </div>
</section>

src/Customer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC Customer</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Customer" asp-action="Index" class="navbar-brand">MVC Customer</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Customer" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - MVC Customer</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>